* Overview

This repository manages my personal Doom Emacs configuration, tailored specifically for data science, literate programming, and productivity workflows on macOS.

It leverages Doom Emacs for a fast, modular, and robust Emacs environment. Beyond sane defaults, this repo adds batteries-included workflows for data science (Python, R), Org-mode (including Org-roam, Hugo blogging, RevealJS presentations), LLM tools ([[https://openai.com][OpenAI]] and Whisper for transcription), and integrates Github Copilot AI completion.

* Complete Set-Up Guide

These are the steps I personally use whenever I need to set-up Emacs again on a new machine.

** Installing Emacs

I installed Emacs on MacOS using the [[https://github.com/d12frosted/homebrew-emacs-plus][emacs+]] version. Detailed instructions are in the repository, including different versions of Emacs and additional options. In short, after installing [[https://brew.sh/][Homebrew]], run:
#+BEGIN_SRC bash
brew tap d12frosted/emacs-plus
brew install emacs-plus --with-imagemagick --with-debug --with-dbus --with-xwidgets --with-retro-gnu-meditate-levitate-icon
#+END_SRC

Then follow homebrew's instructions to add an icon to Emacs.

** Setting up an SSH key for Github

On a terminal, run =ssh-keygen -t ed25519 -C "your_email@example.com"=. Then copy it to the clipboard =pbcopy < ~/.ssh/id_ed25519.pub= and paste it into Github. Do not forget to authorize access to any organizations, if you need.

** Encryption with GPG

1. Install =gnupg= with =brew install gnupg=.
2. Generate a new key with =gpg --full-generate-key=. 
3. Install "pinentry": =brew install pinentry-mac=.
4. Configure GPG to use "pinentry": =echo "pinentry-program /opt/homebrew/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf=.
5. Relod the agent: =gpgconf --kill gpg-agent=.

** Installing dependencies

- Doom: =brew install ripgrep=
- Graphviz: =brew install graphviz=
- Remove any conflicting folder with emacs configs: =rm -rf ~/.emacs.d/=
- Whisper: 
    - Clone repository: =git clone https://github.com/natrys/whisper.el.git <SAME PERSONAL FOLDER YOU WILL USE IN PERSONAL.EL>=
    - Install whisper dependencies: =brew install cmake ffmpeg=
- NPM: =brew install npm=
- Latex: install [[https://www.tug.org/mactex/][MacTeX]]

** Installing Doom and Updating Configurations

1. Install [[https://github.com/doomemacs/doomemacs][doomemacs]].
2. Run `doom doctor` a few times to fix any missing dependencies.
3. Clone this repo into your Doom Emacs directory: =rm -rf ~/.config/doom && git clone git@github.com:guilherme-salome/emacs.git ~/.config/doom=.
4. Copy and edit =personal.el.sample= to =personal.el=, filling in all your paths and personal details.
5. Run =~/.config/emacs/bin/doom sync=.
6. Run =~/.config/emacs/bin/doom env=.
7. Restart Emacs.

** Configuring credentials

gptel:

1. Launch Emacs and visit the file =~/.authinfo.gpg=. Emacs will use your encryption key to load and save your file.
2. Add a new entry with the following: =machine api.openai.com password <YOUR OPENAI API KEY>=.

copilot:

1. Open Emacs and run =M-x copilot-install-server=
2. Login to copilt by running =M-x copilot-login=

* Troubleshooting

gptel:

- If the =~/.authinfo.gpg= file is not working well with your encryption key (i.e., password not fetched by Emacs), you could use the regular unencrypted =~/.authinfo= file. 

latex:

- After installing MacTex, the PATH is modified to include the folder =/Library/TeX/texbin=. You can check if the same PATH is available within Emacs with =(getenv "PATH")=. If the PATHs differ, then you need to run =~/.config/emacs/bin/doom env= and restart Emacs.

* License

This configuration is provided as-is, with no warranty. It is intended for personal use and for other data scientists interested in Emacs-based workflows.
